name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    brances: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: simulated build
      run: |
        export VERSION=$(head -n 1 ./RELEASE_NOTES.md)
        cd ./cmd/api
        cp -R * ../..
        cd ../..
        zip api.zip bookings hello-world

    - name: config aws
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.GHUB_ACTIONS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.GHUB_ACTIONS_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: cp to s3 
      run: |
        export VERSION=$(head -n 1 ./RELEASE_NOTES.md)
        touch bucket_key.md
        touch bucket_version.md
        touch tf_key.sh
        chmod +x tf_key.sh
        cat <<\EOF >> tf_key.sh
        #!/bin/bash
        DIR=$(aws s3 ls s3://jeremy-code-deploy-dev-useast1/api)
        export VERSION=$(head -n 1 ./RELEASE_NOTES.md)
        if [[ -d $DIR$VERSION || -L $DIR$VERSION ]]; then
          echo "It Exists"
          i=1
          while [[ -d $DIR$VERSION-$1 || -L $DIR$VERSION-$i ]]; do 
           let i++;
          done
          aws s3 cp s3://jeremy-code-deploy-dev-useast1/api/${VERSION}-$i/api.zip
          echo "$DIR$VERSION-$i" | cat - bucket_version.md >> temp && mv -f temp bucket_version.md
          head -n 1 bucket_version.md | grep -Eio $VERSION-$i > bucket_key.md
        else
          echo "It Doesn't exist"
          aws s3 cp s3://jeremy-code-deploy-dev-useast1/api/${VERSION}/api.zip
          echo "$DIR$VERSION" | cat - bucket_version.md >> temp && mv -f temp bucket_version.md
          head -n 1 bucket_version.md | grep -Eio $VERSION > bucket_key.md
        fi
        EOF
        ./tf_key.sh



     
