name: Auto Create PR

on:
  push:
    branches:
      - pull-request

jobs:
  createPR:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Pull Request to main
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "pull-request"
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Auto PR from pull-request to main"
        pr_body: "Automatic Pull Request from pull-request branch to main. Please review!"