name: TESTING

on:
    push:
      branches: [ staging-** ]
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
          
      - name: Write branch name to a file
        run: echo ${{ github.ref_name }} > BRANCH_NAME
        
      - name: Archive branch name file
        uses: actions/upload-artifact@v2
        with:
          name: branch-name
          path: BRANCH_NAME

      - name: config aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GHUB_ACTIONS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GHUB_ACTIONS_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify S3 File
        run: |
          aws s3api head-object --bucket jeremy-code-deploy-dev-useast1 --key api/v2.0.0/api.zip

      - name: Post test success comment on commit
        if: success() # This ensures the comment is only posted if the previous steps succeeded
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commitSha = context.sha;
            const message = '🎉 The tests have run successfully!';
            github.rest.repos.createCommitComment({
              ...context.repo,
              commit_sha: commitSha,
              body: message
            });
        