name: TESTING

on:
    pull_request:
      branches: [ main, dev_* ]
      types: [ opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: config aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GHUB_ACTIONS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GHUB_ACTIONS_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify S3 File
        run: |
          aws s3api head-object --bucket jeremy-code-deploy-dev-useast1 --key api/v2.0.0/api.zip
    