name: TESTING

on:
    push:
      branches: [ staging ]
    pull_request:
      branches: [ staging ]
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:     
      - uses: ./.github/workflows/checkout_repo.yaml@main
        with:
          repository: pseudonative/replica-github-action-api
          
      - uses: ./.github/workflows/aws_auth.yaml@main
        with:
          repository: pseudonative/replica-github-action-api
      
      

      - name: Verify S3 File
        run: |
          aws s3api head-object --bucket jeremy-code-deploy-dev-useast1 --key api/v2.0.0/api.zip
          
      - name: Setup GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
  
      - name: Create Pull Request
        run: |
          PR_EXIST=$(gh pr list --base main --head staging | wc -l)
          if [ "$PR_EXIST" -eq "0" ]; then
            gh pr create --base main --head staging --title "Staging Terraform Plan & Apply" --body "Automatic PR created by TESTING workflow"
          fi