name: TESTING

on:
  push:
    branches: [ staging-** ]
  pull_request:
    branches: [ staging-** ]

jobs:
  call-test-workflow:
    uses: pseudonative/reusable_work_flows/.github/workflows/auth_checkout_initial.yaml@main
    with:
      aws_region: 'us-east-1'
      s3_bucket_name: 'jeremy-code-deploy-dev-useast1'
      s3_object_key: 'api/v2.0.0/api.zip'
    secrets:
      aws_access_key_id: ${{ secrets.GHUB_ACTIONS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.GHUB_ACTIONS_ACCESS_KEY }}

