name: TESTING

on:
    push:
      branches: [ staging-** ]
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
          
      - name: Write branch name to a file
        run: echo ${{ github.ref_name }} > BRANCH_NAME
        
      - name: Archive branch name file
        uses: actions/upload-artifact@v2
        with:
          name: branch-name
          path: BRANCH_NAME

      - name: config aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GHUB_ACTIONS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GHUB_ACTIONS_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify S3 File
        run: |
          aws s3api head-object --bucket jeremy-code-deploy-dev-useast1 --key api/v2.0.0/api.zip

      - name: Get branch name
        id: get-branch-name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
  
      - name: Post comment on commit if staging branch
        if: startsWith(env.BRANCH_NAME, 'staging-')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               -d '{"body": "🎉 The tests have run successfully on staging branch!"}' \
               "https://api.github.com/repos/${{ github.repository }}/commits/${GITHUB_SHA}/comments"
               