name: Terraform Apply

on:
  pull_request_review:
    types: [submitted]
 
jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    if: github.event.review.body == '/lgtm_dev'
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: staging
        
      - name: config aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GHUB_ACTIONS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GHUB_ACTIONS_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download Plan Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: tf_plan.yaml
          name: plan
          workflow_conclusion: success
          github_token: ${{secrets.GITHUB_TOKEN}}
          path: terraform
            
      - name: Set Up TF
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve plan.tfout

          