name: Terraform Apply

on:
  pull_request_review:
    types: [submitted]
 
jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    if: github.event.review.body == '/lgtm_dev'
    steps: 
      - name: Determine Branch Name
        id: branch_name
        run: echo "::set-output name=branch::$(echo ${{ github.ref }} | sed 's/refs\/heads\///')"
        
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.branch_name.outputs.branch }}
        
      - name: config aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GHUB_ACTIONS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GHUB_ACTIONS_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download Plan Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: tf_plan.yaml
          name: plan
          workflow_conclusion: success
          github_token: ${{secrets.GITHUB_TOKEN}}
          path: terraform
            
      - name: Set Up TF
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve plan.tfout
        continue-on-error: false  # Continue even if this step fails

      - name: Successful Apply
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -d '{"body":"Terraform Apply was successful!"}'
            
      - name: Comment on PR if Failed
        if: failure()
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -d '{"body":"Terraform Apply failed. Please check the logs for details."}'