name: Terraform Plan

on:
    issue_comment:
      types: [created]

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.GHUB_ACTIONS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.GHUB_ACTIONS_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set Up TF
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_version: 1.5.0

    - name: Terraform Plan
      run: |
        sleep 3
        echo "Terraform Plan"
        sleep 4
        cd terraform/
        terraform init
        terraform plan -out=plan.tfout
        
    - name: Plan for display
      id: tf_plan
      run: |
        cd terraform/
        terraform init
        PLAN_OUTPUT=$(terraform plan)
        echo "::set-output name=plan_output::$PLAN_OUTPUT"

    - name: Comment Terraform Plan
      run: |
          COMMENT_URL=${{ github.event.pull_request.comments_url }}
          if [[ -z "$COMMENT_URL" ]]; then
            echo "Not a PR or can't fetch comment URL"
            exit 0
          fi
          COMMENT_BODY="#### Terraform Plan:\n\`\`\`\n[command]/home/runner/work/_temp/9a653ec7-6d75-4029-9242-a52219aa740c/terraform-bin plan\n\`\`\`"
          curl -s -S -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -X POST --data "{\"body\":\"$COMMENT_BODY\"}" $COMMENT_URL

    - name: Archive Plan File
      uses: actions/upload-artifact@v2
      with:
        name: plan
        path: terraform/plan.tfout
    
 