name: Terraform Plan

on:
    issue_comment:
      types: [created]

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.GHUB_ACTIONS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.GHUB_ACTIONS_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set Up TF
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_version: 1.5.0

    - name: Terraform Plan
      run: |
        sleep 3
        echo "Terraform Plan"
        sleep 4
        cd terraform/
        terraform init
        terraform plan -out=plan.tfout

    - name: Archive Plan File
      uses: actions/upload-artifact@v2
      with:
        name: plan
        path: terraform/plan.tfout
    
    - name: Display Terraform Plan
      run: |
           cd terraform
           plan_contents=$(cat plan.tfout)
           echo "::set-output name=plan_contents::$plan_contents"

    - name: Comment on Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             body: "Terraform Plan Contents:\n\`\`\`hcl\n${{ steps.displayTerraformPlan.outputs.plan_contents }}\n\`\`\`",
           });
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
