name: Terraform Plan

on:
    issue_comment:
      types: [created]

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.GHUB_ACTIONS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.GHUB_ACTIONS_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set Up TF
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_version: 1.5.0

    - name: Terraform Plan for display
      run: |
        cd terraform/
        terraform init
        terraform plan -out=plan.tfout | tee plan_output.txt

    - name: Comment Terraform Plan
      run: |
              COMMENT_URL=${{ github.event.issue.comments_url }}
              if [[ -z "$COMMENT_URL" ]]; then
                echo "Not a PR or can't fetch comment URL"
                exit 0
              fi
              PLAN_OUTPUT=$(<terraform/plan_output.txt)
              PAYLOAD=$(jq -n --arg body "#### Terraform Plan:\n\`\`\`\n$PLAN_OUTPUT\n\`\`\`" '{body: $body}')
              curl -s -S -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                   -H "Content-Type: application/json" \
                   -X POST --data "$PAYLOAD" $COMMENT_URL
        
    - name: Archive Plan File
      uses: actions/upload-artifact@v2
      with:
        name: plan
        path: terraform/plan.tfout
